/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class markovic_milorad_chataplication_NdkPackage_MyNDK */

#ifndef _Included_markovic_milorad_chataplication_NdkPackage_MyNDK
#define _Included_markovic_milorad_chataplication_NdkPackage_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     markovic_milorad_chataplication_NdkPackage_MyNDK
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_markovic_milorad_chataplication_NdkPackage_MyNDK_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
